title: "The Reading Rind"
theme: minima
sass:
  style: compressed

# If your theme supports additional stylesheets:
# For minima, you can use:
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
# And in your main layout (optional advanced step) youâ€™d link custom.css
